### ISSUE TITLE
[Question] Setting user-path based on EDE

### ISSUE THREAD

**Issue by krzysztof-magosa** [randomphrase/company-c-headers#10]
Hi,

You included example how to set `company-c-headers-path-system` from EDE.
I'm trying do the same but with user-path, so it would complete local project headers.
Unfortunately I cannot find name of function/variable in EDE where include-path is stored.
Any idea how to achieve that?

Thanks.

**Comment by randomphrase** [comment]
EDE does not distinguish between user and system paths, instead all headers are searched in what it calls the system include path. Hence you can probably just set the `company-c-headers-path-user` variable from `ede-system-include-path`.

**Comment by krzysztof-magosa** [comment]
Thank you :)
