### ISSUE TITLE
potential duplicates in headers proposition.

### ISSUE THREAD

**Issue by fredericfrances** [randomphrase/company-c-headers#21]
hi,

when using a function to determine include path, company-c-headers may propose same path several times.
it can also be easyly reproduced by setting some duplicate path in  `company-c-headers-path-user'

here is a patch proposal to remove this duplicates.
`diff --git a/company-c-headers.el b/company-c-headers.el
index d217b05..41a83ac 100644
--- a/company-c-headers.el
+++ b/company-c-headers.el
@@ -41,6 +41,7 @@
 
 (require 'company)
 (require 'rx)
+(require 'cl)
 (require 'cl-lib)
 
 (defgroup company-c-headers nil
@@ -143,7 +144,7 @@ Filters on the appropriate regex for the current major mode."
                     (setq next nil)
                     tmp)))
       )
-    candidates
+    (remove-duplicates candidates :test 'equal)
     ))
 
 (defun company-c-headers--meta (candidate)
`

**Comment by linux40** [comment]
Please use `cl-remove-duplicates`. I got a warning from this package for `(require 'cl)`.

**Comment by randomphrase** [comment]
Done, thanks for letting me know.
