### ISSUE TITLE
How to set the path-system under MS Windows?

### ISSUE THREAD

**Issue by SpadedotS** [randomphrase/company-c-headers#24]
I've installed mingw gcc on Windows 10 and I‘ve included the include-path of gcc&g++ in the configuration file like this:
```
(setq company-c-headers-path-system '("C:/MinGW/include" "c:/MinGW/lib/gcc/mingw32/8.2.0/include/c++")) 
```
but the company-frontend didn't work, it just shows Keywords, Classes, etc.
![image](https://user-images.githubusercontent.com/14160477/88450816-698bdc80-ce84-11ea-934b-0782a45d8988.png)

Is there a specific way to include the path under MS Windows? Or should I include the system path of Windows system?

Thank you for your reading. Looking forward to your reply.

**Comment by randomphrase** [comment]
I can see from your screenshot that you are using clangd - in this case you don't need company-c-headers at all because the completions should all be coming from there. That's why you're getting types and other symbols. Check your clangd setup.

**Comment by SpadedotS** [comment]
Thank you for your reply, I've tried not using company-c-backends as a company-backend, and this does work. Thanks a lot!
