### ISSUE TITLE
Conflict with yasnippet

### ISSUE THREAD

**Issue by saintaugustinus** [randomphrase/company-c-headers#6]
Hi I found a problem while using this backend with yasnippet
here is the situation:
i have a snippet for C\C++
when i type ````inc```` and expand it with yasnippet, it will be like this:
````#include <>```` 
the cursor is between '<' and '>'  and this backend work fine now but when i finally choose the header 
it will become like that:
````#include >````

**Comment by Mafeuser** [comment]
please see conclusions at:
https://github.com/capitaomorte/yasnippet/issues/581

**Comment by randomphrase** [comment]
Untested, but have you tried [this guilde](https://www.reddit.com/r/emacs/comments/3r9fic/best_practicestip_for_companymode_andor_yasnippet/) for using yasnippet with company mode? Seems like a way to control which company mode backends get used with yasnippet.

**Comment by saintaugustinus** [comment]
Thanks for your reply~
I have already found another way to solve this

**Comment by Carter-Pro** [comment]
@saintaugustinus  能问下你是怎么解决的吗

**Comment by saintaugustinus** [comment]
@Carter-Pro 把你的snippet改一下
例如inc ==> #include 不要<>合""
哈哈

**Comment by seudut** [comment]
I also meet this issue now, as I also use `company-c-headers` and `yasnippet`. any conclusion to this ?
